baseURL = 'https://undo.studio/'
languageCode = 'en-us'
title = 'undo.studio'

[params]
	description = "Starting a calm, bootstrapped software business from scratch. Sharing first-hand lessons in marketing, engineering, design, support, and everything in between."
